<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login"
           tests="9"
           failures="1"
           errors="0"
           skipped="0"
           time="1.096">
  <properties />
            <testcase name="login2" time="0.079" classname="com.api.test.LoginTest">
                <failure type="java.lang.Exception"
                  message="expectedValue doesn&apos;t match actualValue,actual Value is :200; expected Value is :400"
              >
<![CDATA[java.lang.Exception: expectedValue doesn't match actualValue,actual Value is :200; expected Value is :400
  com.api.utils.Checker.verify(Checker.java:65)
  com.api.utils.Checker.verifyXpath(Checker.java:48)
  com.api.test.LoginTest.login2(LoginTest.java:62)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="login1" time="0.094" classname="com.api.test.LoginTest" />
                <testcase name="login7" time="0.109" classname="com.api.test.LoginTest" />
                <testcase name="login6" time="0.079" classname="com.api.test.LoginTest" />
                <testcase name="login4" time="0.078" classname="com.api.test.LoginTest" />
                <testcase name="login5" time="0.094" classname="com.api.test.LoginTest" />
                <testcase name="login9" time="0.094" classname="com.api.test.LoginTest" />
                <testcase name="login3" time="0.391" classname="com.api.test.LoginTest" />
                <testcase name="login8" time="0.078" classname="com.api.test.LoginTest" />
      
</testsuite>
